require("dotenv").config();

const mongoose = require("mongoose");
const dotenv = require("dotenv");
const Book = require("../models/book");
const connectDB = require("../config/db");

const books = [
  // =====================================================
  // FICTION / CLASSICS
  // =====================================================

  {
    title: "1984",
    author: "George Orwell",
    description: "A dystopian novel about surveillance, totalitarianism, and individual freedom.",
    genres: ["Fiction", "Philosophy"],
    subGenre: "Dystopian",
    language: "English",
    difficulty: "Intermediate",
    pages: 328,
    estimatedReadingHours: 8,
    image: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    rating: 4.7,
    tags: ["dystopia", "politics", "freedom", "surveillance"],
  },

  {
    title: "Animal Farm",
    author: "George Orwell",
    description: "A political allegorical novel exploring power, corruption, and revolution.",
    genres: ["Fiction", "History"],
    subGenre: "Political Satire",
    language: "English",
    difficulty: "Beginner",
    pages: 112,
    estimatedReadingHours: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780451526342-L.jpg",
    rating: 4.6,
    tags: ["politics", "revolution", "satire", "power"],
  },

  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description: "A coming-of-age story exploring justice, racism, morality, and compassion.",
    genres: ["Fiction", "History"],
    subGenre: "Coming of Age",
    language: "English",
    difficulty: "Intermediate",
    pages: 336,
    estimatedReadingHours: 9,
    image: "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg",
    rating: 4.8,
    tags: ["justice", "morality", "family", "society"],
  },

  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description: "A classic novel about wealth, ambition, love, and the American Dream.",
    genres: ["Fiction", "Philosophy"],
    subGenre: "Classic",
    language: "English",
    difficulty: "Intermediate",
    pages: 180,
    estimatedReadingHours: 5,
    image: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    rating: 4.4,
    tags: ["wealth", "love", "ambition", "american-dream"],
  },

  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description: "A classic romance examining relationships, social class, pride, and misunderstandings.",
    genres: ["Fiction", "Romance"],
    subGenre: "Classic Romance",
    language: "English",
    difficulty: "Intermediate",
    pages: 432,
    estimatedReadingHours: 11,
    image: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
    rating: 4.8,
    tags: ["romance", "society", "relationships", "classic"],
  },

  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    description: "A coming-of-age story following a teenager struggling with identity and society.",
    genres: ["Fiction", "Philosophy"],
    subGenre: "Coming of Age",
    language: "English",
    difficulty: "Intermediate",
    pages: 277,
    estimatedReadingHours: 7,
    image: "https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg",
    rating: 4.3,
    tags: ["youth", "identity", "society", "coming-of-age"],
  },

  {
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    description: "A powerful story of friendship, guilt, redemption, and family set across Afghanistan.",
    genres: ["Fiction", "History"],
    subGenre: "Historical Fiction",
    language: "English",
    difficulty: "Intermediate",
    pages: 371,
    estimatedReadingHours: 9,
    image: "https://covers.openlibrary.org/b/isbn/9781594631931-L.jpg",
    rating: 4.8,
    tags: ["friendship", "family", "redemption", "afghanistan"],
  },

  {
    title: "A Thousand Splendid Suns",
    author: "Khaled Hosseini",
    description: "A story of friendship, resilience, family, and survival in Afghanistan.",
    genres: ["Fiction", "History"],
    subGenre: "Historical Fiction",
    language: "English",
    difficulty: "Intermediate",
    pages: 432,
    estimatedReadingHours: 11,
    image: "https://covers.openlibrary.org/b/isbn/9781594489501-L.jpg",
    rating: 4.8,
    tags: ["friendship", "war", "family", "resilience"],
  },

  {
    title: "The Book Thief",
    author: "Markus Zusak",
    description: "A historical novel about a young girl, books, and survival during World War II.",
    genres: ["Fiction", "History"],
    subGenre: "Historical Fiction",
    language: "English",
    difficulty: "Intermediate",
    pages: 584,
    estimatedReadingHours: 14,
    image: "https://covers.openlibrary.org/b/isbn/9780375842207-L.jpg",
    rating: 4.7,
    tags: ["world-war", "books", "family", "survival"],
  },

  {
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    description: "A philosophical tale about friendship, love, responsibility, and human nature.",
    genres: ["Fiction", "Philosophy"],
    subGenre: "Philosophical Fiction",
    language: "English",
    difficulty: "Beginner",
    pages: 96,
    estimatedReadingHours: 2,
    image: "https://covers.openlibrary.org/b/isbn/9780156012195-L.jpg",
    rating: 4.8,
    tags: ["friendship", "love", "philosophy", "life"],
  },

  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    description: "An adventurous fantasy journey following Bilbo Baggins and a company of dwarves.",
    genres: ["Fiction", "Fantasy"],
    subGenre: "High Fantasy",
    language: "English",
    difficulty: "Beginner",
    pages: 310,
    estimatedReadingHours: 8,
    image: "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
    rating: 4.8,
    tags: ["adventure", "fantasy", "dragons", "journey"],
  },

  {
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    description: "An epic fantasy journey to destroy a powerful ring and defeat the forces of evil.",
    genres: ["Fiction", "Fantasy"],
    subGenre: "Epic Fantasy",
    language: "English",
    difficulty: "Advanced",
    pages: 1178,
    estimatedReadingHours: 30,
    image: "https://covers.openlibrary.org/b/isbn/9780544003415-L.jpg",
    rating: 4.9,
    tags: ["fantasy", "adventure", "magic", "epic"],
  },

  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    description: "A philosophical Gothic novel exploring beauty, morality, vanity, and corruption.",
    genres: ["Fiction", "Philosophy"],
    subGenre: "Gothic Fiction",
    language: "English",
    difficulty: "Advanced",
    pages: 254,
    estimatedReadingHours: 7,
    image: "https://covers.openlibrary.org/b/isbn/9780141439570-L.jpg",
    rating: 4.5,
    tags: ["beauty", "morality", "vanity", "gothic"],
  },

  {
    title: "The Old Man and the Sea",
    author: "Ernest Hemingway",
    description: "A short novel about perseverance, struggle, dignity, and determination.",
    genres: ["Fiction", "Philosophy"],
    subGenre: "Literary Fiction",
    language: "English",
    difficulty: "Beginner",
    pages: 128,
    estimatedReadingHours: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780684830490-L.jpg",
    rating: 4.4,
    tags: ["perseverance", "struggle", "determination", "life"],
  },

  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    description: "A young shepherd follows his dreams and searches for his personal legend.",
    genres: ["Fiction", "Self-Help"],
    subGenre: "Philosophical Fiction",
    language: "English",
    difficulty: "Beginner",
    pages: 208,
    estimatedReadingHours: 5,
    image: "https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg",
    rating: 4.6,
    tags: ["dreams", "purpose", "journey", "motivation"],
  },


  // =====================================================
  // SELF HELP / PERSONAL DEVELOPMENT
  // =====================================================

  {
    title: "Atomic Habits",
    author: "James Clear",
    description: "A practical guide to building good habits and breaking bad ones through small improvements.",
    genres: ["Self-Help", "Productivity"],
    subGenre: "Habits",
    language: "English",
    difficulty: "Beginner",
    pages: 320,
    estimatedReadingHours: 8,
    image: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
    rating: 4.8,
    tags: ["habits", "productivity", "discipline", "self-improvement"],
  },

  {
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen R. Covey",
    description: "A classic framework for developing effectiveness, leadership, and personal responsibility.",
    genres: ["Self-Help", "Productivity"],
    subGenre: "Personal Development",
    language: "English",
    difficulty: "Intermediate",
    pages: 464,
    estimatedReadingHours: 12,
    image: "https://covers.openlibrary.org/b/isbn/9781982137274-L.jpg",
    rating: 4.7,
    tags: ["habits", "leadership", "effectiveness", "discipline"],
  },

  {
    title: "How to Win Friends and Influence People",
    author: "Dale Carnegie",
    description: "A practical guide to communication, relationships, influence, and social skills.",
    genres: ["Self-Help", "Psychology"],
    subGenre: "Communication",
    language: "English",
    difficulty: "Beginner",
    pages: 288,
    estimatedReadingHours: 7,
    image: "https://covers.openlibrary.org/b/isbn/9780671027032-L.jpg",
    rating: 4.7,
    tags: ["communication", "relationships", "social-skills", "influence"],
  },

  {
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    description: "A classic personal development book focused on mindset, ambition, and achievement.",
    genres: ["Self-Help", "Finance"],
    subGenre: "Success",
    language: "English",
    difficulty: "Beginner",
    pages: 238,
    estimatedReadingHours: 6,
    image: "https://covers.openlibrary.org/b/isbn/9781585424337-L.jpg",
    rating: 4.6,
    tags: ["success", "wealth", "mindset", "goals"],
  },

  {
    title: "The Power of Now",
    author: "Eckhart Tolle",
    description: "A guide to mindfulness, presence, and reducing psychological suffering.",
    genres: ["Self-Help", "Philosophy"],
    subGenre: "Mindfulness",
    language: "English",
    difficulty: "Intermediate",
    pages: 236,
    estimatedReadingHours: 6,
    image: "https://covers.openlibrary.org/b/isbn/9781577314806-L.jpg",
    rating: 4.6,
    tags: ["mindfulness", "presence", "peace", "awareness"],
  },

  {
    title: "Man's Search for Meaning",
    author: "Viktor E. Frankl",
    description: "A reflection on suffering, meaning, resilience, and the human search for purpose.",
    genres: ["Self-Help", "Psychology"],
    subGenre: "Meaning",
    language: "English",
    difficulty: "Intermediate",
    pages: 165,
    estimatedReadingHours: 4,
    image: "https://covers.openlibrary.org/b/isbn/9780807014271-L.jpg",
    rating: 4.8,
    tags: ["meaning", "purpose", "resilience", "psychology"],
  },

  {
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    description: "A direct approach to values, responsibility, limitations, and personal growth.",
    genres: ["Self-Help", "Philosophy"],
    subGenre: "Personal Development",
    language: "English",
    difficulty: "Beginner",
    pages: 224,
    estimatedReadingHours: 6,
    image: "https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg",
    rating: 4.3,
    tags: ["mindset", "values", "growth", "life"],
  },

  {
    title: "The Mountain Is You",
    author: "Brianna Wiest",
    description: "A guide to overcoming self-sabotage and transforming emotional patterns.",
    genres: ["Self-Help", "Psychology"],
    subGenre: "Self-Sabotage",
    language: "English",
    difficulty: "Beginner",
    pages: 288,
    estimatedReadingHours: 7,
    image: "https://covers.openlibrary.org/b/isbn/9781945796067-L.jpg",
    rating: 4.5,
    tags: ["self-sabotage", "growth", "emotions", "healing"],
  },

  {
    title: "The Power of Habit",
    author: "Charles Duhigg",
    description: "An exploration of how habits work and how they can be changed.",
    genres: ["Self-Help", "Psychology"],
    subGenre: "Habits",
    language: "English",
    difficulty: "Intermediate",
    pages: 371,
    estimatedReadingHours: 9,
    image: "https://covers.openlibrary.org/b/isbn/9780812981605-L.jpg",
    rating: 4.6,
    tags: ["habits", "behavior", "productivity", "change"],
  },

  {
    title: "The Four Agreements",
    author: "Don Miguel Ruiz",
    description: "A practical philosophy built around four principles for personal freedom.",
    genres: ["Self-Help", "Philosophy"],
    subGenre: "Personal Growth",
    language: "English",
    difficulty: "Beginner",
    pages: 160,
    estimatedReadingHours: 4,
    image: "https://covers.openlibrary.org/b/isbn/9781878424310-L.jpg",
    rating: 4.6,
    tags: ["freedom", "mindset", "growth", "wisdom"],
  },

  {
    title: "The Courage to Be Disliked",
    author: "Ichiro Kishimi and Fumitake Koga",
    description: "A dialogue exploring Adlerian psychology, freedom, relationships, and self-acceptance.",
    genres: ["Self-Help", "Psychology"],
    subGenre: "Adlerian Psychology",
    language: "English",
    difficulty: "Intermediate",
    pages: 288,
    estimatedReadingHours: 7,
    image: "https://covers.openlibrary.org/b/isbn/9781501197277-L.jpg",
    rating: 4.5,
    tags: ["psychology", "freedom", "confidence", "relationships"],
  },

  {
    title: "Ikigai",
    author: "Héctor García and Francesc Miralles",
    description: "An exploration of Japanese ideas about purpose, longevity, and meaningful living.",
    genres: ["Self-Help", "Philosophy"],
    subGenre: "Purpose",
    language: "English",
    difficulty: "Beginner",
    pages: 208,
    estimatedReadingHours: 5,
    image: "https://covers.openlibrary.org/b/isbn/9780143130727-L.jpg",
    rating: 4.4,
    tags: ["purpose", "japan", "happiness", "longevity"],
  },

  {
    title: "Deep Work",
    author: "Cal Newport",
    description: "A practical guide to focused work and developing valuable cognitive skills.",
    genres: ["Self-Help", "Productivity"],
    subGenre: "Focus",
    language: "English",
    difficulty: "Intermediate",
    pages: 304,
    estimatedReadingHours: 8,
    image: "https://covers.openlibrary.org/b/id/15150797-L.jpg",
    rating: 4.7,
    tags: ["focus", "productivity", "work", "concentration"],
  },

  {
    title: "Digital Minimalism",
    author: "Cal Newport",
    description: "A philosophy for using technology intentionally while reducing digital distractions.",
    genres: ["Self-Help", "Technology"],
    subGenre: "Digital Wellness",
    language: "English",
    difficulty: "Intermediate",
    pages: 304,
    estimatedReadingHours: 8,
    image: "https://covers.openlibrary.org/b/isbn/9780525536512-L.jpg",
    rating: 4.5,
    tags: ["technology", "minimalism", "focus", "digital-life"],
  },


  // =====================================================
  // PSYCHOLOGY
  // =====================================================

  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    description: "An exploration of the two systems that shape human judgment and decision-making.",
    genres: ["Psychology", "Science"],
    subGenre: "Cognitive Psychology",
    language: "English",
    difficulty: "Advanced",
    pages: 499,
    estimatedReadingHours: 13,
    image: "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
    rating: 4.6,
    tags: ["psychology", "decision-making", "bias", "thinking"],
  },

  {
    title: "Predictably Irrational",
    author: "Dan Ariely",
    description: "An examination of hidden forces that influence irrational human decisions.",
    genres: ["Psychology", "Science"],
    subGenre: "Behavioral Economics",
    language: "English",
    difficulty: "Intermediate",
    pages: 304,
    estimatedReadingHours: 8,
    image: "https://covers.openlibrary.org/b/isbn/9780061353246-L.jpg",
    rating: 4.3,
    tags: ["behavior", "decisions", "bias", "economics"],
  },

  {
    title: "Influence",
    author: "Robert B. Cialdini",
    description: "An analysis of psychological principles that influence human behavior and persuasion.",
    genres: ["Psychology", "Business"],
    subGenre: "Persuasion",
    language: "English",
    difficulty: "Intermediate",
    pages: 592,
    estimatedReadingHours: 15,
    image: "https://covers.openlibrary.org/b/isbn/9780061241895-L.jpg",
    rating: 4.7,
    tags: ["persuasion", "influence", "behavior", "marketing"],
  },

  {
    title: "Emotional Intelligence",
    author: "Daniel Goleman",
    description: "An exploration of emotional intelligence and its role in relationships and success.",
    genres: ["Psychology", "Self-Help"],
    subGenre: "Emotional Intelligence",
    language: "English",
    difficulty: "Intermediate",
    pages: 352,
    estimatedReadingHours: 9,
    image: "https://covers.openlibrary.org/b/isbn/9780553383713-L.jpg",
    rating: 4.5,
    tags: ["emotions", "intelligence", "relationships", "success"],
  },

  {
    title: "The Psychology of Money",
    author: "Morgan Housel",
    description: "Timeless lessons about how behavior and psychology influence financial decisions.",
    genres: ["Psychology", "Finance"],
    subGenre: "Financial Psychology",
    language: "English",
    difficulty: "Beginner",
    pages: 256,
    estimatedReadingHours: 6,
    image: "https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg",
    rating: 4.7,
    tags: ["money", "behavior", "finance", "investing"],
  },

  {
    title: "Quiet",
    author: "Susan Cain",
    description: "An exploration of introversion and the strengths of quiet personalities.",
    genres: ["Psychology", "Self-Help"],
    subGenre: "Personality",
    language: "English",
    difficulty: "Intermediate",
    pages: 368,
    estimatedReadingHours: 9,
    image: "https://covers.openlibrary.org/b/isbn/9780307352156-L.jpg",
    rating: 4.5,
    tags: ["introversion", "personality", "society", "confidence"],
  },

  {
    title: "Grit",
    author: "Angela Duckworth",
    description: "An examination of how passion and perseverance contribute to long-term achievement.",
    genres: ["Psychology", "Self-Help"],
    subGenre: "Motivation",
    language: "English",
    difficulty: "Intermediate",
    pages: 352,
    estimatedReadingHours: 9,
    image: "https://covers.openlibrary.org/b/isbn/9781501111105-L.jpg",
    rating: 4.5,
    tags: ["grit", "motivation", "success", "perseverance"],
  },

  {
    title: "Flow",
    author: "Mihaly Csikszentmihalyi",
    description: "A study of optimal experience and the psychological state of deep engagement.",
    genres: ["Psychology", "Self-Help"],
    subGenre: "Positive Psychology",
    language: "English",
    difficulty: "Advanced",
    pages: 304,
    estimatedReadingHours: 8,
    image: "https://covers.openlibrary.org/b/isbn/9780061339202-L.jpg",
    rating: 4.6,
    tags: ["flow", "happiness", "focus", "psychology"],
  },

  {
    title: "The Happiness Hypothesis",
    author: "Jonathan Haidt",
    description: "A blend of ancient wisdom and modern psychology explaining human happiness.",
    genres: ["Psychology", "Philosophy"],
    subGenre: "Positive Psychology",
    language: "English",
    difficulty: "Advanced",
    pages: 320,
    estimatedReadingHours: 8,
    image: "https://covers.openlibrary.org/b/isbn/9780465028025-L.jpg",
    rating: 4.4,
    tags: ["happiness", "psychology", "wisdom", "mind"],
  },

  {
    title: "The Man Who Mistook His Wife for a Hat",
    author: "Oliver Sacks",
    description: "Fascinating neurological case studies exploring the complexity of the human mind.",
    genres: ["Psychology", "Science"],
    subGenre: "Neurology",
    language: "English",
    difficulty: "Intermediate",
    pages: 320,
    estimatedReadingHours: 8,
    image: "https://covers.openlibrary.org/b/isbn/9780679724536-L.jpg",
    rating: 4.4,
    tags: ["brain", "neurology", "mind", "medicine"],
  },

  {
    title: "Blink",
    author: "Malcolm Gladwell",
    description: "An exploration of rapid cognition, intuition, and unconscious decision-making.",
    genres: ["Psychology", "Self-Help"],
    subGenre: "Decision Making",
    language: "English",
    difficulty: "Intermediate",
    pages: 296,
    estimatedReadingHours: 7,
    image: "https://covers.openlibrary.org/b/isbn/9780316010665-L.jpg",
    rating: 4.2,
    tags: ["intuition", "decisions", "psychology", "thinking"],
  },

  {
    title: "Outliers",
    author: "Malcolm Gladwell",
    description: "An investigation into the hidden factors behind extraordinary success.",
    genres: ["Psychology", "Self-Help"],
    subGenre: "Success Psychology",
    language: "English",
    difficulty: "Intermediate",
    pages: 309,
    estimatedReadingHours: 8,
    image: "https://covers.openlibrary.org/b/isbn/9780316017930-L.jpg",
    rating: 4.4,
    tags: ["success", "achievement", "culture", "psychology"],
  },


  // =====================================================
  // BUSINESS / LEADERSHIP
  // =====================================================

  {
    title: "The Lean Startup",
    author: "Eric Ries",
    description: "A methodology for building businesses through experimentation and validated learning.",
    genres: ["Business", "Technology"],
    subGenre: "Entrepreneurship",
    language: "English",
    difficulty: "Intermediate",
    pages: 336,
    estimatedReadingHours: 8,
    image: "https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg",
    rating: 4.4,
    tags: ["startup", "business", "entrepreneurship", "innovation"],
  },

  {
    title: "Zero to One",
    author: "Peter Thiel",
    description: "A discussion of innovation, startups, competition, and creating new businesses.",
    genres: ["Business", "Technology"],
    subGenre: "Startups",
    language: "English",
    difficulty: "Intermediate",
    pages: 224,
    estimatedReadingHours: 6,
    image: "https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg",
    rating: 4.4,
    tags: ["startups", "innovation", "technology", "business"],
  },

  {
    title: "Good to Great",
    author: "Jim Collins",
    description: "Research-based insights into how companies transform from good organizations into great ones.",
    genres: ["Business", "Self-Help"],
    subGenre: "Management",
    language: "English",
    difficulty: "Advanced",
    pages: 400,
    estimatedReadingHours: 10,
    image: "https://covers.openlibrary.org/b/isbn/9780066620992-L.jpg",
    rating: 4.6,
    tags: ["leadership", "business", "management", "success"],
  },

  {
    title: "Start with Why",
    author: "Simon Sinek",
    description: "A framework for understanding how purpose drives leadership and organizations.",
    genres: ["Business", "Self-Help"],
    subGenre: "Leadership",
    language: "English",
    difficulty: "Beginner",
    pages: 256,
    estimatedReadingHours: 6,
    image: "https://covers.openlibrary.org/b/isbn/9781591846444-L.jpg",
    rating: 4.5,
    tags: ["leadership", "purpose", "business", "motivation"],
  },

  {
    title: "Leaders Eat Last",
    author: "Simon Sinek",
    description: "An exploration of leadership, trust, teamwork, and organizational culture.",
    genres: ["Business", "Psychology"],
    subGenre: "Leadership",
    language: "English",
    difficulty: "Intermediate",
    pages: 368,
    estimatedReadingHours: 9,
    image: "https://covers.openlibrary.org/b/isbn/9781591848011-L.jpg",
    rating: 4.5,
    tags: ["leadership", "teamwork", "culture", "trust"],
  },

  {
    title: "The Hard Thing About Hard Things",
    author: "Ben Horowitz",
    description: "Practical lessons about building and managing startups through difficult situations.",
    genres: ["Business", "Self-Help"],
    subGenre: "Entrepreneurship",
    language: "English",
    difficulty: "Advanced",
    pages: 304,
    estimatedReadingHours: 8,
    image: "https://covers.openlibrary.org/b/isbn/9780062273208-L.jpg",
    rating: 4.6,
    tags: ["startups", "leadership", "entrepreneurship", "management"],
  },

  {
    title: "The 4-Hour Workweek",
    author: "Timothy Ferriss",
    description: "Ideas for redesigning work, productivity, lifestyle, and personal freedom.",
    genres: ["Business", "Productivity"],
    subGenre: "Lifestyle Design",
    language: "English",
    difficulty: "Intermediate",
    pages: 416,
    estimatedReadingHours: 10,
    image: "https://covers.openlibrary.org/b/isbn/9780307465351-L.jpg",
    rating: 4.2,
    tags: ["productivity", "business", "freedom", "lifestyle"],
  },

  {
    title: "The Personal MBA",
    author: "Josh Kaufman",
    description: "An introduction to essential business concepts without requiring a formal MBA.",
    genres: ["Business", "Self-Help"],
    subGenre: "Business Fundamentals",
    language: "English",
    difficulty: "Intermediate",
    pages: 464,
    estimatedReadingHours: 12,
    image: "https://covers.openlibrary.org/b/isbn/9781591845577-L.jpg",
    rating: 4.5,
    tags: ["business", "management", "marketing", "finance"],
  },

  {
    title: "Rework",
    author: "Jason Fried and David Heinemeier Hansson",
    description: "A practical and unconventional approach to starting and running a business.",
    genres: ["Business", "Productivity"],
    subGenre: "Entrepreneurship",
    language: "English",
    difficulty: "Beginner",
    pages: 288,
    estimatedReadingHours: 6,
    image: "https://covers.openlibrary.org/b/isbn/9780307463746-L.jpg",
    rating: 4.4,
    tags: ["business", "startups", "productivity", "entrepreneurship"],
  },

  {
    title: "Built to Last",
    author: "Jim Collins and Jerry I. Porras",
    description: "Research into successful companies and the practices that help them endure.",
    genres: ["Business", "Self-Help"],
    subGenre: "Management",
    language: "English",
    difficulty: "Advanced",
    pages: 368,
    estimatedReadingHours: 9,
    image: "https://covers.openlibrary.org/b/isbn/9780060516406-L.jpg",
    rating: 4.3,
    tags: ["business", "management", "leadership", "companies"],
  },


  // =====================================================
  // FINANCE
  // =====================================================

  {
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    description: "A personal finance classic about financial education, assets, and wealth building.",
    genres: ["Finance", "Self-Help"],
    subGenre: "Personal Finance",
    language: "English",
    difficulty: "Beginner",
    pages: 336,
    estimatedReadingHours: 8,
    image: "https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg",
    rating: 4.5,
    tags: ["money", "wealth", "investing", "finance"],
  },

  {
    title: "The Intelligent Investor",
    author: "Benjamin Graham",
    description: "A classic guide to value investing, risk management, and long-term financial thinking.",
    genres: ["Finance", "Business"],
    subGenre: "Investing",
    language: "English",
    difficulty: "Advanced",
    pages: 640,
    estimatedReadingHours: 16,
    image: "https://covers.openlibrary.org/b/isbn/9780060555665-L.jpg",
    rating: 4.6,
    tags: ["investing", "stocks", "finance", "value-investing"],
  },

  {
    title: "The Millionaire Next Door",
    author: "Thomas J. Stanley and William D. Danko",
    description: "Research into the habits and behaviors commonly found among wealthy households.",
    genres: ["Finance", "Self-Help"],
    subGenre: "Wealth Building",
    language: "English",
    difficulty: "Beginner",
    pages: 272,
    estimatedReadingHours: 7,
    image: "https://covers.openlibrary.org/b/isbn/9781589795471-L.jpg",
    rating: 4.5,
    tags: ["wealth", "saving", "money", "habits"],
  },

  {
    title: "I Will Teach You to Be Rich",
    author: "Ramit Sethi",
    description: "A practical system for managing money, investing, saving, and spending intentionally.",
    genres: ["Finance", "Self-Help"],
    subGenre: "Personal Finance",
    language: "English",
    difficulty: "Beginner",
    pages: 352,
    estimatedReadingHours: 9,
    image: "https://covers.openlibrary.org/b/isbn/9781523505746-L.jpg",
    rating: 4.6,
    tags: ["money", "saving", "investing", "finance"],
  },

  {
    title: "A Random Walk Down Wall Street",
    author: "Burton G. Malkiel",
    description: "An accessible explanation of investing, markets, and portfolio strategy.",
    genres: ["Finance", "Business"],
    subGenre: "Investing",
    language: "English",
    difficulty: "Advanced",
    pages: 448,
    estimatedReadingHours: 11,
    image: "https://covers.openlibrary.org/b/isbn/9780393330335-L.jpg",
    rating: 4.4,
    tags: ["investing", "stocks", "markets", "finance"],
  },


  // =====================================================
  // SCIENCE
  // =====================================================

  {
    title: "Sapiens",
    author: "Yuval Noah Harari",
    description: "A sweeping history of humanity from early humans to modern civilization.",
    genres: ["Science", "History"],
    subGenre: "Human History",
    language: "English",
    difficulty: "Intermediate",
    pages: 464,
    estimatedReadingHours: 12,
    image: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
    rating: 4.7,
    tags: ["humanity", "history", "evolution", "civilization"],
  },

  {
    title: "Homo Deus",
    author: "Yuval Noah Harari",
    description: "A speculative exploration of humanity's future and emerging technologies.",
    genres: ["Science", "Philosophy"],
    subGenre: "Future Studies",
    language: "English",
    difficulty: "Advanced",
    pages: 464,
    estimatedReadingHours: 12,
    image: "https://covers.openlibrary.org/b/isbn/9780062464316-L.jpg",
    rating: 4.5,
    tags: ["future", "technology", "humanity", "AI"],
  },

  {
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    description: "An accessible introduction to cosmology, space, time, black holes, and the universe.",
    genres: ["Science"],
    subGenre: "Physics",
    language: "English",
    difficulty: "Advanced",
    pages: 256,
    estimatedReadingHours: 7,
    image: "https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg",
    rating: 4.6,
    tags: ["physics", "space", "universe", "cosmology"],
  },

  {
    title: "The Selfish Gene",
    author: "Richard Dawkins",
    description: "An influential explanation of evolution through the perspective of genes.",
    genres: ["Science"],
    subGenre: "Evolution",
    language: "English",
    difficulty: "Advanced",
    pages: 384,
    estimatedReadingHours: 10,
    image: "https://covers.openlibrary.org/b/isbn/9780198788607-L.jpg",
    rating: 4.6,
    tags: ["evolution", "biology", "genes", "science"],
  },

  {
    title: "Cosmos",
    author: "Carl Sagan",
    description: "A journey through astronomy, science, evolution, and humanity's place in the universe.",
    genres: ["Science", "Philosophy"],
    subGenre: "Astronomy",
    language: "English",
    difficulty: "Intermediate",
    pages: 384,
    estimatedReadingHours: 10,
    image: "https://covers.openlibrary.org/b/isbn/9780345539434-L.jpg",
    rating: 4.8,
    tags: ["space", "astronomy", "science", "universe"],
  },

  {
    title: "The Gene",
    author: "Siddhartha Mukherjee",
    description: "A comprehensive history and explanation of genetics and heredity.",
    genres: ["Science", "History"],
    subGenre: "Genetics",
    language: "English",
    difficulty: "Advanced",
    pages: 608,
    estimatedReadingHours: 16,
    image: "https://covers.openlibrary.org/b/isbn/9781476733524-L.jpg",
    rating: 4.6,
    tags: ["genetics", "biology", "medicine", "DNA"],
  },

  {
    title: "Astrophysics for People in a Hurry",
    author: "Neil deGrasse Tyson",
    description: "A concise introduction to fundamental concepts in astrophysics and the universe.",
    genres: ["Science"],
    subGenre: "Astrophysics",
    language: "English",
    difficulty: "Beginner",
    pages: 224,
    estimatedReadingHours: 5,
    image: "https://covers.openlibrary.org/b/isbn/9780393609394-L.jpg",
    rating: 4.5,
    tags: ["space", "physics", "universe", "astronomy"],
  },

  {
    title: "The Body",
    author: "Bill Bryson",
    description: "A fascinating tour through the human body and modern medical knowledge.",
    genres: ["Science"],
    subGenre: "Human Biology",
    language: "English",
    difficulty: "Intermediate",
    pages: 464,
    estimatedReadingHours: 12,
    image: "https://covers.openlibrary.org/b/isbn/9780385539302-L.jpg",
    rating: 4.6,
    tags: ["body", "biology", "medicine", "health"],
  },


  // =====================================================
  // HISTORY
  // =====================================================

  {
    title: "Guns, Germs, and Steel",
    author: "Jared Diamond",
    description: "An examination of geography, environment, technology, and the development of civilizations.",
    genres: ["History", "Science"],
    subGenre: "World History",
    language: "English",
    difficulty: "Advanced",
    pages: 528,
    estimatedReadingHours: 14,
    image: "https://covers.openlibrary.org/b/isbn/9780393317558-L.jpg",
    rating: 4.5,
    tags: ["history", "civilization", "geography", "society"],
  },

  {
    title: "The Silk Roads",
    author: "Peter Frankopan",
    description: "A history of the world centered around the regions connected by the Silk Roads.",
    genres: ["History"],
    subGenre: "World History",
    language: "English",
    difficulty: "Advanced",
    pages: 672,
    estimatedReadingHours: 17,
    image: "https://covers.openlibrary.org/b/isbn/9781101912379-L.jpg",
    rating: 4.5,
    tags: ["history", "silk-road", "trade", "civilization"],
  },

  {
    title: "Prisoners of Geography",
    author: "Tim Marshall",
    description: "An accessible explanation of how geography shapes global politics and international relations.",
    genres: ["History", "Science"],
    subGenre: "Geopolitics",
    language: "English",
    difficulty: "Intermediate",
    pages: 304,
    estimatedReadingHours: 8,
    image: "https://covers.openlibrary.org/b/isbn/9781783962433-L.jpg",
    rating: 4.5,
    tags: ["geography", "politics", "countries", "geopolitics"],
  },

  {
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    description: "The diary of a young girl hiding from the Nazis during World War II.",
    genres: ["History", "Biography"],
    subGenre: "World War II",
    language: "English",
    difficulty: "Intermediate",
    pages: 352,
    estimatedReadingHours: 9,
    image: "https://covers.openlibrary.org/b/isbn/9780553296983-L.jpg",
    rating: 4.7,
    tags: ["world-war", "holocaust", "diary", "history"],
  },

  {
    title: "Alexander the Great",
    author: "Philip Freeman",
    description: "A biography of one of history's most influential military leaders.",
    genres: ["History", "Biography"],
    subGenre: "Ancient History",
    language: "English",
    difficulty: "Intermediate",
    pages: 416,
    estimatedReadingHours: 10,
    image: "https://covers.openlibrary.org/b/isbn/9781416589716-L.jpg",
    rating: 4.4,
    tags: ["alexander", "greece", "war", "ancient-history"],
  },

  {
    title: "A People's History of the United States",
    author: "Howard Zinn",
    description: "A history of the United States emphasizing perspectives often left outside traditional narratives.",
    genres: ["History"],
    subGenre: "American History",
    language: "English",
    difficulty: "Advanced",
    pages: 768,
    estimatedReadingHours: 20,
    image: "https://covers.openlibrary.org/b/isbn/9780062397348-L.jpg",
    rating: 4.5,
    tags: ["america", "history", "society", "politics"],
  },

  {
    title: "India After Gandhi",
    author: "Ramachandra Guha",
    description: "A comprehensive history of independent India and its political and social development.",
    genres: ["History"],
    subGenre: "Indian History",
    language: "English",
    difficulty: "Advanced",
    pages: 944,
    estimatedReadingHours: 24,
    image: "https://covers.openlibrary.org/b/isbn/9780060958589-L.jpg",
    rating: 4.7,
    tags: ["india", "history", "politics", "independence"],
  },

  {
    title: "The Discovery of India",
    author: "Jawaharlal Nehru",
    description: "A historical and philosophical exploration of India's civilization and cultural development.",
    genres: ["History", "Philosophy"],
    subGenre: "Indian History",
    language: "English",
    difficulty: "Advanced",
    pages: 646,
    estimatedReadingHours: 17,
    image: "https://covers.openlibrary.org/b/isbn/9780143031031-L.jpg",
    rating: 4.6,
    tags: ["india", "history", "culture", "civilization"],
  },


  // =====================================================
  // BIOGRAPHY
  // =====================================================

  {
    title: "Steve Jobs",
    author: "Walter Isaacson",
    description: "A detailed biography of Apple's co-founder and technology visionary.",
    genres: ["Biography", "Technology"],
    subGenre: "Technology Biography",
    language: "English",
    difficulty: "Intermediate",
    pages: 656,
    estimatedReadingHours: 16,
    image: "https://covers.openlibrary.org/b/isbn/9781451648539-L.jpg",
    rating: 4.6,
    tags: ["steve-jobs", "apple", "technology", "innovation"],
  },

  {
    title: "Elon Musk",
    author: "Walter Isaacson",
    description: "A biography examining the life, businesses, ambitions, and controversies of Elon Musk.",
    genres: ["Biography", "Technology"],
    subGenre: "Technology Biography",
    language: "English",
    difficulty: "Intermediate",
    pages: 688,
    estimatedReadingHours: 17,
    image: "https://covers.openlibrary.org/b/isbn/9781982181284-L.jpg",
    rating: 4.3,
    tags: ["technology", "entrepreneurship", "innovation", "business"],
  },

  {
    title: "Becoming",
    author: "Michelle Obama",
    description: "A memoir exploring family, identity, career, public life, and personal growth.",
    genres: ["Biography", "Self-Help"],
    subGenre: "Memoir",
    language: "English",
    difficulty: "Intermediate",
    pages: 448,
    estimatedReadingHours: 11,
    image: "https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg",
    rating: 4.8,
    tags: ["memoir", "leadership", "family", "growth"],
  },

  {
    title: "Long Walk to Freedom",
    author: "Nelson Mandela",
    description: "Nelson Mandela's autobiography covering his life and struggle against apartheid.",
    genres: ["Biography", "History"],
    subGenre: "Autobiography",
    language: "English",
    difficulty: "Advanced",
    pages: 656,
    estimatedReadingHours: 17,
    image: "https://covers.openlibrary.org/b/isbn/9780316548182-L.jpg",
    rating: 4.8,
    tags: ["mandela", "freedom", "leadership", "history"],
  },

  {
    title: "Wings of Fire",
    author: "A.P.J. Abdul Kalam",
    description: "An inspiring autobiography describing the life and career of India's former president and scientist.",
    genres: ["Biography", "Self-Help"],
    subGenre: "Autobiography",
    language: "English",
    difficulty: "Beginner",
    pages: 180,
    estimatedReadingHours: 5,
    image: "https://covers.openlibrary.org/b/isbn/9788173711466-L.jpg",
    rating: 4.7,
    tags: ["india", "science", "motivation", "leadership"],
  },

  {
    title: "My Experiments with Truth",
    author: "Mahatma Gandhi",
    description: "An autobiography reflecting on Gandhi's life, principles, experiments, and philosophy.",
    genres: ["Biography", "Philosophy"],
    subGenre: "Autobiography",
    language: "English",
    difficulty: "Advanced",
    pages: 480,
    estimatedReadingHours: 12,
    image: "https://covers.openlibrary.org/b/isbn/9780140447973-L.jpg",
    rating: 4.6,
    tags: ["gandhi", "india", "philosophy", "truth"],
  },


  // =====================================================
  // PHILOSOPHY
  // =====================================================

  {
    title: "Meditations",
    author: "Marcus Aurelius",
    description: "Personal reflections on Stoicism, virtue, discipline, and living a meaningful life.",
    genres: ["Philosophy", "Self-Help"],
    subGenre: "Stoicism",
    language: "English",
    difficulty: "Intermediate",
    pages: 256,
    estimatedReadingHours: 6,
    image: "https://covers.openlibrary.org/b/isbn/9780140449334-L.jpg",
    rating: 4.7,
    tags: ["stoicism", "wisdom", "discipline", "virtue"],
  },

  {
    title: "Letters from a Stoic",
    author: "Seneca",
    description: "Letters exploring Stoic philosophy, resilience, mortality, and practical wisdom.",
    genres: ["Philosophy", "Self-Help"],
    subGenre: "Stoicism",
    language: "English",
    difficulty: "Advanced",
    pages: 416,
    estimatedReadingHours: 11,
    image: "https://covers.openlibrary.org/b/isbn/9780141395852-L.jpg",
    rating: 4.6,
    tags: ["stoicism", "wisdom", "resilience", "philosophy"],
  },

  {
    title: "The Republic",
    author: "Plato",
    description: "A foundational philosophical dialogue exploring justice, politics, education, and society.",
    genres: ["Philosophy", "History"],
    subGenre: "Political Philosophy",
    language: "English",
    difficulty: "Advanced",
    pages: 416,
    estimatedReadingHours: 11,
    image: "https://covers.openlibrary.org/b/isbn/9780140455113-L.jpg",
    rating: 4.6,
    tags: ["plato", "justice", "politics", "philosophy"],
  },

  {
    title: "Thus Spoke Zarathustra",
    author: "Friedrich Nietzsche",
    description: "A philosophical work exploring morality, values, individuality, and human transformation.",
    genres: ["Philosophy"],
    subGenre: "Existential Philosophy",
    language: "English",
    difficulty: "Advanced",
    pages: 352,
    estimatedReadingHours: 10,
    image: "https://covers.openlibrary.org/b/isbn/9780140441185-L.jpg",
    rating: 4.4,
    tags: ["nietzsche", "philosophy", "morality", "individuality"],
  },

  {
    title: "The Stranger",
    author: "Albert Camus",
    description: "An existential novel examining absurdity, alienation, morality, and meaning.",
    genres: ["Philosophy", "Fiction"],
    subGenre: "Existentialism",
    language: "English",
    difficulty: "Intermediate",
    pages: 123,
    estimatedReadingHours: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780679720201-L.jpg",
    rating: 4.5,
    tags: ["absurdism", "existentialism", "meaning", "philosophy"],
  },

  {
    title: "The Art of War",
    author: "Sun Tzu",
    description: "An ancient strategic text covering planning, leadership, competition, and conflict.",
    genres: ["Philosophy", "Business"],
    subGenre: "Strategy",
    language: "English",
    difficulty: "Intermediate",
    pages: 273,
    estimatedReadingHours: 6,
    image: "https://covers.openlibrary.org/b/isbn/9781599869773-L.jpg",
    rating: 4.6,
    tags: ["strategy", "leadership", "war", "competition"],
  },

  {
    title: "Beyond Good and Evil",
    author: "Friedrich Nietzsche",
    description: "A philosophical critique of traditional morality, truth, and philosophical assumptions.",
    genres: ["Philosophy"],
    subGenre: "Moral Philosophy",
    language: "English",
    difficulty: "Advanced",
    pages: 240,
    estimatedReadingHours: 7,
    image: "https://covers.openlibrary.org/b/isbn/9780140449235-L.jpg",
    rating: 4.4,
    tags: ["morality", "truth", "philosophy", "nietzsche"],
  },

  {
    title: "The Myth of Sisyphus",
    author: "Albert Camus",
    description: "An influential philosophical essay exploring absurdity, meaning, and existence.",
    genres: ["Philosophy"],
    subGenre: "Absurdism",
    language: "English",
    difficulty: "Advanced",
    pages: 176,
    estimatedReadingHours: 5,
    image: "https://covers.openlibrary.org/b/isbn/9780525564454-L.jpg",
    rating: 4.5,
    tags: ["absurdism", "meaning", "existence", "philosophy"],
  },


  // =====================================================
  // FANTASY
  // =====================================================

  {
    title: "Harry Potter and the Chamber of Secrets",
    author: "J.K. Rowling",
    description: "Harry returns to Hogwarts and discovers a mysterious chamber threatening the school.",
    genres: ["Fantasy", "Fiction"],
    subGenre: "Young Adult Fantasy",
    language: "English",
    difficulty: "Beginner",
    pages: 341,
    estimatedReadingHours: 8,
    image: "https://covers.openlibrary.org/b/isbn/9780439064866-L.jpg",
    rating: 4.8,
    tags: ["magic", "wizard", "hogwarts", "adventure"],
  },

  {
    title: "Harry Potter and the Prisoner of Azkaban",
    author: "J.K. Rowling",
    description: "Harry's third year at Hogwarts introduces a dangerous escaped prisoner and hidden truths.",
    genres: ["Fantasy", "Fiction"],
    subGenre: "Young Adult Fantasy",
    language: "English",
    difficulty: "Beginner",
    pages: 435,
    estimatedReadingHours: 10,
    image: "https://covers.openlibrary.org/b/isbn/9780439136365-L.jpg",
    rating: 4.9,
    tags: ["magic", "hogwarts", "adventure", "mystery"],
  },

  {
    title: "Harry Potter and the Goblet of Fire",
    author: "J.K. Rowling",
    description: "Harry competes in the dangerous Triwizard Tournament while a dark threat returns.",
    genres: ["Fantasy", "Fiction"],
    subGenre: "Young Adult Fantasy",
    language: "English",
    difficulty: "Intermediate",
    pages: 734,
    estimatedReadingHours: 18,
    image: "https://covers.openlibrary.org/b/isbn/9780439139601-L.jpg",
    rating: 4.8,
    tags: ["magic", "tournament", "hogwarts", "adventure"],
  },

  {
    title: "Harry Potter and the Order of the Phoenix",
    author: "J.K. Rowling",
    description: "Harry faces growing danger while resisting denial of Voldemort's return.",
    genres: ["Fantasy", "Fiction"],
    subGenre: "Young Adult Fantasy",
    language: "English",
    difficulty: "Intermediate",
    pages: 870,
    estimatedReadingHours: 21,
    image: "https://covers.openlibrary.org/b/isbn/9780439358071-L.jpg",
    rating: 4.8,
    tags: ["magic", "hogwarts", "resistance", "adventure"],
  },

  {
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    description: "An epic fantasy following the life and legends of the mysterious Kvothe.",
    genres: ["Fantasy", "Fiction"],
    subGenre: "Epic Fantasy",
    language: "English",
    difficulty: "Advanced",
    pages: 662,
    estimatedReadingHours: 17,
    image: "https://covers.openlibrary.org/b/isbn/9780756404741-L.jpg",
    rating: 4.7,
    tags: ["magic", "adventure", "fantasy", "storytelling"],
  },

  {
    title: "Mistborn",
    author: "Brandon Sanderson",
    description: "A fantasy adventure about rebellion, magic, and a society ruled by an immortal emperor.",
    genres: ["Fantasy", "Fiction"],
    subGenre: "Epic Fantasy",
    language: "English",
    difficulty: "Intermediate",
    pages: 672,
    estimatedReadingHours: 17,
    image: "https://covers.openlibrary.org/b/isbn/9780765311788-L.jpg",
    rating: 4.7,
    tags: ["magic", "rebellion", "fantasy", "adventure"],
  },

  {
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    description: "An epic fantasy of political conflict, family alliances, war, and power.",
    genres: ["Fantasy", "Fiction"],
    subGenre: "Epic Fantasy",
    language: "English",
    difficulty: "Advanced",
    pages: 694,
    estimatedReadingHours: 18,
    image: "https://covers.openlibrary.org/b/isbn/9780553593716-L.jpg",
    rating: 4.7,
    tags: ["fantasy", "politics", "war", "dragons"],
  },

  {
    title: "Coraline",
    author: "Neil Gaiman",
    description: "A young girl discovers a strange parallel world hiding dangerous secrets.",
    genres: ["Fantasy", "Fiction"],
    subGenre: "Dark Fantasy",
    language: "English",
    difficulty: "Beginner",
    pages: 176,
    estimatedReadingHours: 4,
    image: "https://covers.openlibrary.org/b/isbn/9780380807345-L.jpg",
    rating: 4.5,
    tags: ["fantasy", "adventure", "mystery", "dark-fantasy"],
  },


  // =====================================================
  // MYSTERY / THRILLER
  // =====================================================

  {
    title: "The Da Vinci Code",
    author: "Dan Brown",
    description: "A fast-paced mystery involving symbols, secrets, historical conspiracies, and puzzles.",
    genres: ["Mystery", "Fiction"],
    subGenre: "Conspiracy Thriller",
    language: "English",
    difficulty: "Intermediate",
    pages: 689,
    estimatedReadingHours: 17,
    image: "https://covers.openlibrary.org/b/isbn/9780307474278-L.jpg",
    rating: 4.4,
    tags: ["mystery", "conspiracy", "symbols", "thriller"],
  },

  {
    title: "Angels and Demons",
    author: "Dan Brown",
    description: "A thriller involving secret societies, science, religion, and a dangerous conspiracy.",
    genres: ["Mystery", "Fiction"],
    subGenre: "Conspiracy Thriller",
    language: "English",
    difficulty: "Intermediate",
    pages: 736,
    estimatedReadingHours: 18,
    image: "https://covers.openlibrary.org/b/isbn/9781416524793-L.jpg",
    rating: 4.5,
    tags: ["mystery", "conspiracy", "science", "thriller"],
  },

  {
    title: "Gone Girl",
    author: "Gillian Flynn",
    description: "A psychological thriller about a disappearance, marriage, deception, and manipulation.",
    genres: ["Mystery", "Psychology"],
    subGenre: "Psychological Thriller",
    language: "English",
    difficulty: "Advanced",
    pages: 432,
    estimatedReadingHours: 11,
    image: "https://covers.openlibrary.org/b/isbn/9780553418361-L.jpg",
    rating: 4.5,
    tags: ["thriller", "mystery", "marriage", "psychology"],
  },

  {
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    description: "A dark mystery involving a missing woman, corruption, secrets, and investigation.",
    genres: ["Mystery", "Fiction"],
    subGenre: "Crime Thriller",
    language: "English",
    difficulty: "Advanced",
    pages: 465,
    estimatedReadingHours: 12,
    image: "https://covers.openlibrary.org/b/isbn/9780307949486-L.jpg",
    rating: 4.5,
    tags: ["mystery", "crime", "thriller", "investigation"],
  },

  {
    title: "The Silent Patient",
    author: "Alex Michaelides",
    description: "A psychological mystery about a woman who stops speaking after a shocking crime.",
    genres: ["Mystery", "Psychology"],
    subGenre: "Psychological Thriller",
    language: "English",
    difficulty: "Intermediate",
    pages: 336,
    estimatedReadingHours: 8,
    image: "https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg",
    rating: 4.4,
    tags: ["mystery", "psychology", "crime", "thriller"],
  },

  {
    title: "The Murder of Roger Ackroyd",
    author: "Agatha Christie",
    description: "A classic Hercule Poirot mystery involving murder, secrets, and an unexpected solution.",
    genres: ["Mystery", "Fiction"],
    subGenre: "Detective Fiction",
    language: "English",
    difficulty: "Intermediate",
    pages: 288,
    estimatedReadingHours: 7,
    image: "https://covers.openlibrary.org/b/isbn/9780062074001-L.jpg",
    rating: 4.6,
    tags: ["mystery", "detective", "murder", "poirot"],
  },

  {
    title: "And Then There Were None",
    author: "Agatha Christie",
    description: "Ten strangers are brought together on an isolated island where they begin dying one by one.",
    genres: ["Mystery", "Fiction"],
    subGenre: "Mystery",
    language: "English",
    difficulty: "Intermediate",
    pages: 272,
    estimatedReadingHours: 7,
    image: "https://covers.openlibrary.org/b/isbn/9780062073488-L.jpg",
    rating: 4.7,
    tags: ["mystery", "murder", "detective", "suspense"],
  },

  {
    title: "The Hound of the Baskervilles",
    author: "Arthur Conan Doyle",
    description: "Sherlock Holmes investigates a mysterious curse surrounding an English family.",
    genres: ["Mystery", "Fiction"],
    subGenre: "Detective Fiction",
    language: "English",
    difficulty: "Intermediate",
    pages: 256,
    estimatedReadingHours: 6,
    image: "https://covers.openlibrary.org/b/isbn/9780140437504-L.jpg",
    rating: 4.6,
    tags: ["sherlock-holmes", "mystery", "detective", "crime"],
  },


  // =====================================================
  // TECHNOLOGY
  // =====================================================

  {
    title: "The Innovators",
    author: "Walter Isaacson",
    description: "A history of the pioneers who created the digital revolution.",
    genres: ["Technology", "History"],
    subGenre: "Technology History",
    language: "English",
    difficulty: "Intermediate",
    pages: 560,
    estimatedReadingHours: 14,
    image: "https://covers.openlibrary.org/b/isbn/9781476708706-L.jpg",
    rating: 4.5,
    tags: ["technology", "innovation", "computing", "history"],
  },

  {
    title: "Life 3.0",
    author: "Max Tegmark",
    description: "An exploration of artificial intelligence and its possible impact on humanity's future.",
    genres: ["Technology", "Science"],
    subGenre: "Artificial Intelligence",
    language: "English",
    difficulty: "Advanced",
    pages: 384,
    estimatedReadingHours: 10,
    image: "https://covers.openlibrary.org/b/isbn/9781101946596-L.jpg",
    rating: 4.4,
    tags: ["AI", "technology", "future", "artificial-intelligence"],
  },

  {
    title: "Superintelligence",
    author: "Nick Bostrom",
    description: "A philosophical and technical examination of advanced artificial intelligence and its risks.",
    genres: ["Technology", "Philosophy"],
    subGenre: "Artificial Intelligence",
    language: "English",
    difficulty: "Advanced",
    pages: 352,
    estimatedReadingHours: 10,
    image: "https://covers.openlibrary.org/b/isbn/9780198739838-L.jpg",
    rating: 4.4,
    tags: ["AI", "technology", "future", "AI-safety"],
  },

  // =====================================================
  // ADDITIONAL POPULAR BOOKS
  // =====================================================

  {
    title: "The 5 AM Club",
    author: "Robin Sharma",
    description: "A personal development framework centered around early mornings, focus, and personal mastery.",
    genres: ["Self-Help", "Productivity"],
    subGenre: "Personal Development",
    language: "English",
    difficulty: "Beginner",
    pages: 336,
    estimatedReadingHours: 8,
    image: "https://covers.openlibrary.org/b/isbn/9781443456623-L.jpg",
    rating: 4.3,
    tags: ["morning", "productivity", "discipline", "habits"],
  },

  {
    title: "Make Time",
    author: "Jake Knapp and John Zeratsky",
    description: "Practical strategies for creating more focus and meaningful time in everyday life.",
    genres: ["Productivity", "Self-Help"],
    subGenre: "Time Management",
    language: "English",
    difficulty: "Beginner",
    pages: 304,
    estimatedReadingHours: 7,
    image: "https://covers.openlibrary.org/b/isbn/9780525539986-L.jpg",
    rating: 4.4,
    tags: ["productivity", "time", "focus", "habits"],
  },

  {
    title: "Essentialism",
    author: "Greg McKeown",
    description: "A philosophy for focusing on what truly matters and eliminating unnecessary commitments.",
    genres: ["Productivity", "Self-Help"],
    subGenre: "Focus",
    language: "English",
    difficulty: "Beginner",
    pages: 272,
    estimatedReadingHours: 7,
    image: "https://covers.openlibrary.org/b/isbn/9780804137386-L.jpg",
    rating: 4.6,
    tags: ["focus", "productivity", "minimalism", "priorities"],
  },

  {
    title: "The One Thing",
    author: "Gary Keller and Jay Papasan",
    description: "A productivity framework focused on identifying and prioritizing the most important task.",
    genres: ["Productivity", "Self-Help"],
    subGenre: "Focus",
    language: "English",
    difficulty: "Beginner",
    pages: 240,
    estimatedReadingHours: 6,
    image: "https://covers.openlibrary.org/b/isbn/9781885167774-L.jpg",
    rating: 4.5,
    tags: ["productivity", "focus", "goals", "priorities"],
  },

  {
    title: "Can't Hurt Me",
    author: "David Goggins",
    description: "A memoir and personal development story about overcoming limitations and developing mental toughness.",
    genres: ["Self-Help", "Biography"],
    subGenre: "Mental Toughness",
    language: "English",
    difficulty: "Intermediate",
    pages: 364,
    estimatedReadingHours: 9,
    image: "https://covers.openlibrary.org/b/isbn/9781544512280-L.jpg",
    rating: 4.7,
    tags: ["discipline", "mental-toughness", "motivation", "resilience"],
  },

  {
    title: "The Psychology of Achievement",
    author: "Brian Tracy",
    description: "Strategies for improving performance, goals, motivation, and personal achievement.",
    genres: ["Self-Help", "Psychology"],
    subGenre: "Achievement",
    language: "English",
    difficulty: "Beginner",
    pages: 288,
    estimatedReadingHours: 7,
    image: "https://covers.openlibrary.org/b/isbn/9780671735168-L.jpg",
    rating: 4.3,
    tags: ["achievement", "goals", "motivation", "success"],
  },

  {
    title: "The Monk Who Sold His Ferrari",
    author: "Robin Sharma",
    description: "A fictional story about transforming one's life through discipline, purpose, and wisdom.",
    genres: ["Self-Help", "Fiction"],
    subGenre: "Personal Development",
    language: "English",
    difficulty: "Beginner",
    pages: 198,
    estimatedReadingHours: 5,
    image: "https://covers.openlibrary.org/b/isbn/9780062515674-L.jpg",
    rating: 4.4,
    tags: ["purpose", "discipline", "wisdom", "success"],
  },

  {
    title: "Do Epic Shit",
    author: "Ankur Warikoo",
    description: "Practical thoughts on career, money, relationships, and personal growth.",
    genres: ["Self-Help", "Business"],
    subGenre: "Personal Development",
    language: "English",
    difficulty: "Beginner",
    pages: 200,
    estimatedReadingHours: 5,
    image: "https://covers.openlibrary.org/b/isbn/9789390166268-L.jpg",
    rating: 4.3,
    tags: ["career", "growth", "money", "motivation"],
  },

  {
    title: "The Rudest Book Ever",
    author: "Shwetabh Gangwar",
    description: "A direct and unconventional discussion about confidence, thinking, and personal responsibility.",
    genres: ["Self-Help", "Psychology"],
    subGenre: "Personal Development",
    language: "English",
    difficulty: "Beginner",
    pages: 248,
    estimatedReadingHours: 6,
    image: "https://covers.openlibrary.org/b/isbn/9789388754138-L.jpg",
    rating: 4.2,
    tags: ["confidence", "mindset", "growth", "life"],
  },

  {
    title: "The Almanack of Naval Ravikant",
    author: "Eric Jorgenson",
    description: "A collection of Naval Ravikant's ideas about wealth, happiness, judgment, and lifelong learning.",
    genres: ["Self-Help", "Finance"],
    subGenre: "Wealth and Happiness",
    language: "English",
    difficulty: "Intermediate",
    pages: 242,
    estimatedReadingHours: 6,
    image: "https://covers.openlibrary.org/b/isbn/9781544514215-L.jpg",
    rating: 4.7,
    tags: ["wealth", "happiness", "learning", "business"],
  },

  {
    title: "The Compound Effect",
    author: "Darren Hardy",
    description: "An explanation of how small choices and consistent actions create significant long-term results.",
    genres: ["Self-Help", "Productivity"],
    subGenre: "Habits",
    language: "English",
    difficulty: "Beginner",
    pages: 176,
    estimatedReadingHours: 4,
    image: "https://covers.openlibrary.org/b/isbn/9781593157241-L.jpg",
    rating: 4.4,
    tags: ["habits", "consistency", "success", "growth"],
  },

  {
    title: "The Magic of Thinking Big",
    author: "David J. Schwartz",
    description: "A classic personal development book about confidence, ambition, and positive thinking.",
    genres: ["Self-Help", "Psychology"],
    subGenre: "Mindset",
    language: "English",
    difficulty: "Beginner",
    pages: 320,
    estimatedReadingHours: 8,
    image: "https://covers.openlibrary.org/b/isbn/9780671646783-L.jpg",
    rating: 4.5,
    tags: ["confidence", "mindset", "success", "goals"],
  },

  {
    title: "Getting Things Done",
    author: "David Allen",
    description: "A productivity methodology for organizing tasks, commitments, and projects.",
    genres: ["Productivity", "Self-Help"],
    subGenre: "Time Management",
    language: "English",
    difficulty: "Intermediate",
    pages: 352,
    estimatedReadingHours: 9,
    image: "https://covers.openlibrary.org/b/isbn/9780142000281-L.jpg",
    rating: 4.4,
    tags: ["productivity", "organization", "tasks", "time-management"],
  },

  {
    title: "The Effective Executive",
    author: "Peter F. Drucker",
    description: "A foundational management book about effectiveness, priorities, and decision-making.",
    genres: ["Business", "Productivity"],
    subGenre: "Management",
    language: "English",
    difficulty: "Advanced",
    pages: 208,
    estimatedReadingHours: 5,
    image: "https://covers.openlibrary.org/b/isbn/9780060833459-L.jpg",
    rating: 4.5,
    tags: ["management", "leadership", "effectiveness", "business"],
  },

  {
    title: "The 48 Laws of Power",
    author: "Robert Greene",
    description: "A study of historical strategies and principles surrounding power and influence.",
    genres: ["Business", "Psychology"],
    subGenre: "Strategy",
    language: "English",
    difficulty: "Advanced",
    pages: 452,
    estimatedReadingHours: 11,
    image: "https://covers.openlibrary.org/b/isbn/9780140280197-L.jpg",
    rating: 4.4,
    tags: ["power", "strategy", "influence", "leadership"],
  },

  {
    title: "The Laws of Human Nature",
    author: "Robert Greene",
    description: "An exploration of human behavior, motivations, emotions, and social dynamics.",
    genres: ["Psychology", "Self-Help"],
    subGenre: "Human Behavior",
    language: "English",
    difficulty: "Advanced",
    pages: 624,
    estimatedReadingHours: 16,
    image: "https://covers.openlibrary.org/b/isbn/9780143111375-L.jpg",
    rating: 4.6,
    tags: ["psychology", "human-nature", "behavior", "relationships"],
  },

  {
    title: "The Design of Everyday Things",
    author: "Don Norman",
    description: "An introduction to human-centered design and how products should work for people.",
    genres: ["Technology", "Psychology"],
    subGenre: "Design",
    language: "English",
    difficulty: "Intermediate",
    pages: 368,
    estimatedReadingHours: 9,
    image: "https://covers.openlibrary.org/b/isbn/9780465050659-L.jpg",
    rating: 4.6,
    tags: ["design", "UX", "technology", "human-centered-design"],
  },

  {
    title: "Clean Code",
    author: "Robert C. Martin",
    description: "A practical guide to writing readable, maintainable, and professional software.",
    genres: ["Technology", "Self-Help"],
    subGenre: "Programming",
    language: "English",
    difficulty: "Advanced",
    pages: 464,
    estimatedReadingHours: 12,
    image: "https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg",
    rating: 4.7,
    tags: ["programming", "software", "clean-code", "development"],
  },

  {
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt and David Thomas",
    description: "Practical principles and techniques for becoming a better software developer.",
    genres: ["Technology", "Self-Help"],
    subGenre: "Programming",
    language: "English",
    difficulty: "Advanced",
    pages: 352,
    estimatedReadingHours: 9,
    image: "https://covers.openlibrary.org/b/isbn/9780135957059-L.jpg",
    rating: 4.8,
    tags: ["programming", "software", "development", "career"],
  },

  {
    title: "The Phoenix Project",
    author: "Gene Kim, Kevin Behr and George Spafford",
    description: "A novel that teaches DevOps, IT management, collaboration, and software delivery principles.",
    genres: ["Technology", "Business"],
    subGenre: "DevOps",
    language: "English",
    difficulty: "Intermediate",
    pages: 432,
    estimatedReadingHours: 10,
    image: "https://covers.openlibrary.org/b/isbn/9780988262591-L.jpg",
    rating: 4.6,
    tags: ["devops", "IT", "software", "business"],
  },

  {
    title: "The Code Book",
    author: "Simon Singh",
    description: "A history of cryptography, codes, ciphers, and the mathematics behind secret communication.",
    genres: ["Technology", "History"],
    subGenre: "Cryptography",
    language: "English",
    difficulty: "Intermediate",
    pages: 432,
    estimatedReadingHours: 11,
    image: "https://covers.openlibrary.org/b/isbn/9780385495325-L.jpg",
    rating: 4.5,
    tags: ["cryptography", "coding", "mathematics", "technology"],
  },
];

const seedBooks = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    console.log("MongoDB Connected");

    const existingTitles = await Book.find(
      {},
      { title: 1 }
    ).lean();

    const existingTitleSet = new Set(
      existingTitles.map((book) =>
        book.title.toLowerCase().trim()
      )
    );

    const booksToInsert = books.filter(
      (book) =>
        !existingTitleSet.has(
          book.title.toLowerCase().trim()
        )
    );

    if (booksToInsert.length === 0) {
      console.log(
        "All seed books already exist. Nothing to insert."
      );

      await mongoose.connection.close();

      return;
    }

    const insertedBooks = await Book.insertMany(
      booksToInsert
    );

    console.log(
      `${insertedBooks.length} new books inserted successfully.`
    );

    const totalBooks = await Book.countDocuments();

    console.log(
      `Total books in database: ${totalBooks}`
    );

    await mongoose.connection.close();

    console.log("MongoDB connection closed.");

  } catch (error) {

    console.error(
      "Error seeding books:",
      error.message
    );

    await mongoose.connection.close();

    process.exit(1);
  }
};

seedBooks();